spring.application.name=maharishi-vidya-mandir-school
spring.profiles.active=dev
# enable OpenAPI generation and Swagger UI for the dev profile
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# optional: explicit UI path
springdoc.swagger-ui.path=/swagger-ui/index.html

